export const CHEMICAL_ITEMS = [
  {
    isEditable: false,
    key: 1,
    label: "Ethylene Chlorohydrin",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: false,
    key: 2,
    label: "Ethylene Glycol",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: false,
    key: 3,
    label: "Ethylene Oxide",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 4,
    label: "Formaldehyde",
    limit: [0, 400],
    value: 15.1,
  },
  {
    isEditable: true,
    key: 5,
    label: "H2",
    limit: [0, 400],
    value: 50,
  },
  {
    isEditable: true,
    key: 6,
    label: "Hexamethylenediamine",
    limit: [0, 400],
    value: 1.4,
  },
  {
    isEditable: true,
    key: 7,
    label: "Isophthalic Acid",
    limit: [0, 400],
    value: 0.9,
  },
  {
    isEditable: true,
    key: 8,
    label: "Maleic Anhydride",
    limit: [0, 400],
    value: 1.8,
  },
  {
    isEditable: true,
    key: 9,
    label: "Melamine",
    limit: [0, 400],
    value: 1.6,
  },
  {
    isEditable: true,
    key: 10,
    label: "Methanol",
    limit: [0, 400],
    value: 62.9,
  },
  {
    isEditable: true,
    key: 11,
    label: "Methyl Methacrylate",
    limit: [0, 400],
    value: 3.2,
  },
  {
    isEditable: true,
    key: 12,
    label: "Methyl Tertbutyl Ether",
    limit: [0, 400],
    value: 16.3,
  },
  {
    isEditable: true,
    key: 13,
    label: "Methylene Diphenyl Isocyanate",
    limit: [0, 400],
    value: 4.3,
  },
  {
    isEditable: true,
    key: 14,
    label: "Monoammonium Phosphate",
    limit: [0, 400],
    value: 24.2,
  },
  {
    isEditable: true,
    key: 15,
    label: "Nitric Acid",
    limit: [0, 400],
    value: 48,
  },
  {
    isEditable: true,
    key: 16,
    label: "Nitrile Butadiene",
    limit: [0, 400],
    value: 0.9,
  },
  {
    isEditable: true,
    key: 17,
    label: "Phthalic Anhydride",
    limit: [0, 400],
    value: 3.5,
  },
  {
    isEditable: true,
    key: 18,
    label: "Polyacrylonitrile",
    limit: [0, 400],
    value: 1.9,
  },
  {
    isEditable: true,
    key: 19,
    label: "Polyamide 6",
    limit: [0, 400],
    value: 4.5,
  },
  {
    isEditable: true,
    key: 20,
    label: "Polyamide 66",
    limit: [0, 400],
    value: 2.6,
  },
  {
    isEditable: true,
    key: 21,
    label: "Polybutadiene",
    limit: [0, 400],
    value: 3.8,
  },
  {
    isEditable: true,
    key: 22,
    label: "Polycarbonate",
    limit: [0, 400],
    value: 3.9,
  },
  {
    isEditable: true,
    key: 23,
    label: "Polyethylene",
    limit: [0, 400],
    value: 80.6,
  },
  {
    isEditable: true,
    key: 24,
    label: "Polyethylene Terephthalate",
    limit: [0, 400],
    value: 63.2,
  },
  {
    isEditable: true,
    key: 25,
    label: "Polymethyl Methacrylate",
    limit: [0, 400],
    value: 1.9,
  },
  {
    isEditable: true,
    key: 26,
    label: "Polypropylene",
    limit: [0, 400],
    value: 49.9,
  },
  {
    isEditable: true,
    key: 27,
    label: "Polystyrene",
    limit: [0, 400],
    value: 15.2,
  },
  {
    isEditable: true,
    key: 28,
    label: "Polyvinyl Acetate",
    limit: [0, 400],
    value: 2.5,
  },
  {
    isEditable: true,
    key: 29,
    label: "Polyvinyl Chloride",
    limit: [0, 400],
    value: 30.3,
  },
  {
    isEditable: true,
    key: 30,
    label: "Propylene Oxide",
    limit: [0, 400],
    value: 8.1,
  },
  {
    isEditable: true,
    key: 31,
    label: "Styrene",
    limit: [0, 400],
    value: 27.4,
  },
  {
    isEditable: true,
    key: 32,
    label: "Styrene Acrylonitrile",
    limit: [0, 400],
    value: 5.5,
  },
  {
    isEditable: true,
    key: 33,
    label: "Styrene Butadiene",
    limit: [0, 400],
    value: 5.5,
  },
  {
    isEditable: false,
    key: 34,
    label: "Terephthalic Acid",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 35,
    label: "Toluene Diisocyanate",
    limit: [0, 400],
    value: 2.5,
  },
  {
    isEditable: true,
    key: 36,
    label: "Urea",
    limit: [0, 400],
    value: 169.3,
  },
  {
    isEditable: true,
    key: 37,
    label: "Urea Ammonium Nitrate",
    limit: [0, 400],
    value: 41.6,
  },
  {
    isEditable: true,
    key: 38,
    label: "Vinyl Acetate",
    limit: [0, 400],
    value: 5.9,
  },
  {
    isEditable: true,
    key: 39,
    label: "Vinyl Chloride",
    limit: [0, 400],
    value: 17.4,
  },
  {
    isEditable: false,
    key: 40,
    label: "Energy",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: false,
    key: 41,
    label: "Electricity",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 42,
    label: "Ethylbenzene",
    limit: [0, 400],
    value: 39,
  },
  {
    isEditable: true,
    key: 43,
    label: "Acrylic Acid",
    limit: [0, 400],
    value: 7.7,
  },
  {
    isEditable: false,
    key: 44,
    label: "Nitrobenzene",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 45,
    label: "Isopropanol",
    limit: [0, 400],
    value: 2.2,
  },
  {
    isEditable: false,
    key: 46,
    label: "Butyraldehyde",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 47,
    label: "N-Butanol",
    limit: [0, 400],
    value: 5.2,
  },
  {
    isEditable: true,
    key: 48,
    label: "EVA Copolymer",
    limit: [0, 400],
    value: 2.9,
  },
  {
    isEditable: true,
    key: 49,
    label: "EPDM",
    limit: [0, 400],
    value: 1.5,
  },
  {
    isEditable: true,
    key: 50,
    label: "ENB",
    limit: [0, 400],
    value: 0.07,
  },
  {
    isEditable: false,
    key: 51,
    label: "Trans 1,4 Hexadiene",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: false,
    key: 52,
    label: "Allyl Chloride",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 53,
    label: "Epichlorohydrin",
    limit: [0, 400],
    value: 2,
  },
  {
    isEditable: false,
    key: 54,
    label: "Chlorine",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 55,
    label: "Glycerol",
    limit: [0, 400],
    value: 4,
  },
  {
    isEditable: true,
    key: 56,
    label: "Propylene Glycol",
    limit: [0, 400],
    value: 1.88,
  },
  {
    isEditable: true,
    key: 57,
    label: "Isobutanol",
    limit: [0, 400],
    value: 5.2,
  },
  {
    isEditable: true,
    key: 58,
    label: "Acetylene",
    limit: [0, 400],
    value: 1.9,
  },
  {
    isEditable: true,
    key: 59,
    label: "1,4 Butanediol",
    limit: [0, 400],
    value: 3,
  },
  {
    isEditable: true,
    key: 60,
    label: "BADGE/DGEBA",
    limit: [0, 400],
    value: 10,
  },
  {
    isEditable: true,
    key: 61,
    label: "Acetaldehyde",
    limit: [0, 400],
    value: 1.3,
  },
  {
    isEditable: false,
    key: 62,
    label: "Diethanolamine (DEA)",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 63,
    label: "Ethyl Acetate",
    limit: [0, 400],
    value: 4,
  },
  {
    isEditable: false,
    key: 64,
    label: "2-Butoxyethanol/EGBE",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 65,
    label: "Ethylene Dichloride",
    limit: [0, 400],
    value: 47.7,
  },
  {
    isEditable: false,
    key: 66,
    label: "2 Ethylhexyl Acrylate",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 67,
    label: "N Butyl Acrylate",
    limit: [0, 400],
    value: 4.8,
  },
  {
    isEditable: false,
    key: 68,
    label: "Ethyl Acrylate",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 69,
    label: "Methyl Acrylate",
    limit: [0, 400],
    value: 0.2,
  },
  {
    isEditable: false,
    key: 70,
    label: "Dinitrotoluene",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 71,
    label: "Diethylene Glycol",
    limit: [0, 400],
    value: 2.6,
  },
  {
    isEditable: false,
    key: 72,
    label: "Dichloropropylene",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 73,
    label: "Hydrogen Cyanide",
    limit: [0, 400],
    value: 1,
  },
  {
    isEditable: true,
    key: 74,
    label: "Acrolein",
    limit: [0, 400],
    value: 1.002,
  },
  {
    isEditable: false,
    key: 75,
    label: "Allyl Alcohol",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 76,
    label: "Benzoic Acid",
    limit: [0, 400],
    value: 0.5491,
  },
  {
    isEditable: true,
    key: 77,
    label: "Carbon Disulphide",
    limit: [0, 400],
    value: 1,
  },
  {
    isEditable: false,
    key: 78,
    label: "Carbon Tetrachloride",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: false,
    key: 79,
    label: "Chlorobenzene",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 80,
    label: "Chloroform",
    limit: [0, 400],
    value: 0.066,
  },
  {
    isEditable: false,
    key: 81,
    label: "Crotonaldehyde",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: false,
    key: 82,
    label: "Cyclohexanol",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 83,
    label: "Cyclohexanone",
    limit: [0, 400],
    value: 6.4,
  },
  {
    isEditable: true,
    key: 84,
    label: "Peracetic Acid",
    limit: [0, 400],
    value: 0.3,
  },
  {
    isEditable: false,
    key: 85,
    label: "Perchloroethylene",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: false,
    key: 86,
    label: "Phosgene",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: false,
    key: 87,
    label: "Toluene Diamine",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: false,
    key: 88,
    label: "Trichloroethylene",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 89,
    label: "Triethylene Glycol",
    limit: [0, 400],
    value: 0.415,
  },
  {
    isEditable: false,
    key: 90,
    label: "Sodium Nitrite",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: false,
    key: 91,
    label: "Nitrogen Dioxide",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: false,
    key: 92,
    label: "Nitric Oxide",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 93,
    label: "Potassium Hydroxide",
    limit: [0, 400],
    value: 2.84,
  },
  {
    isEditable: true,
    key: 94,
    label: "Calcium Hydroxide",
    limit: [0, 400],
    value: 30,
  },
  {
    isEditable: true,
    key: 95,
    label: "PBT",
    limit: [0, 400],
    value: 1.7,
  },
  {
    isEditable: false,
    key: 96,
    label: "Caprolactone",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: false,
    key: 97,
    label: "PCL",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 98,
    label: "Pentaerithrytol",
    limit: [0, 400],
    value: 0.5,
  },
  {
    isEditable: false,
    key: 99,
    label: "Glyptal",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: false,
    key: 100,
    label: "SMA",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 101,
    label: "PEG",
    limit: [0, 400],
    value: 0.6,
  },
  {
    isEditable: true,
    key: 102,
    label: "Tetrahydrofuran",
    limit: [0, 400],
    value: 1.46,
  },
  {
    isEditable: true,
    key: 103,
    label: "PTMEG",
    limit: [0, 400],
    value: 1,
  },
  {
    isEditable: true,
    key: 104,
    label: "PPG",
    limit: [0, 400],
    value: 1.64,
  },
  {
    isEditable: false,
    key: 105,
    label: "PBO",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: false,
    key: 106,
    label: "Butylene Oxide",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: false,
    key: 107,
    label: "PA/POM",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 108,
    label: "POM Copolymer",
    limit: [0, 400],
    value: 1.9,
  },
  {
    isEditable: false,
    key: 109,
    label: "Trioxane",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 110,
    label: "PPO",
    limit: [0, 400],
    value: 0.5,
  },
  {
    isEditable: false,
    key: 111,
    label: "2,6 Dimethylphenol",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: false,
    key: 112,
    label: "Hypochlorous Acid",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 113,
    label: "Hydrochloric Acid",
    limit: [0, 400],
    value: 14.8,
  },
  {
    isEditable: true,
    key: 114,
    label: "Sulphuric Acid",
    limit: [0, 400],
    value: 231,
  },
  {
    isEditable: false,
    key: 115,
    label: "Hydroxyl Amine",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: false,
    key: 116,
    label: "Nitrous Acid",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 117,
    label: "Phosphoric Acid",
    limit: [0, 400],
    value: 86.63,
  },
  {
    isEditable: false,
    key: 118,
    label: "Sucrose",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: true,
    key: 119,
    label: "Ethanol",
    limit: [0, 400],
    value: 79.92,
  },
];

export const CHEMICAL_PARTS = [
  { key: "0,1", value: "0,1" },
  { key: "2,2", value: "2,2" },
  { key: "3,3", value: "3,3" },
  { key: "4,4", value: "4,4" },
  { key: "5,5", value: "5,5" },
  { key: "6,9", value: "6,9" },
];
