export const CHEMICAL_PARTS = [
  { key: "0,1", value: "0,1" },
  { key: "2,2", value: "2,2" },
  { key: "3,3", value: "3,3" },
  { key: "4,4", value: "4,4" },
  { key: "5,5", value: "5,5" },
  { key: "6,9", value: "6,9" },
];

export const CHEMICAL_ITEMS = [
  {
    isEditable: 3.5 !== 0,
    key: 1,
    label: "2 Ethyl Hexanol",
    limit: [0, 400],
    value: 3.5,
  },
  {
    isEditable: 8.8 !== 0,
    key: 2,
    label: "Abs",
    limit: [0, 400],
    value: 8.8,
  },
  {
    isEditable: 11.8 !== 0,
    key: 3,
    label: "Acetic Acid",
    limit: [0, 400],
    value: 11.8,
  },
  {
    isEditable: 6.1 !== 0,
    key: 4,
    label: "Acetone",
    limit: [0, 400],
    value: 6.1,
  },
  {
    isEditable: 5.4 !== 0,
    key: 5,
    label: "Acrylonitrile",
    limit: [0, 400],
    value: 5.4,
  },
  {
    isEditable: 2.9 !== 0,
    key: 6,
    label: "Adipic Acid",
    limit: [0, 400],
    value: 2.9,
  },
  {
    isEditable: 1.5 !== 0,
    key: 7,
    label: "Adiponitrile",
    limit: [0, 400],
    value: 1.5,
  },
  {
    isEditable: 169.7 !== 0,
    key: 8,
    label: "Ammonia",
    limit: [0, 400],
    value: 169.7,
  },
  {
    isEditable: 47.8 !== 0,
    key: 9,
    label: "Ammonium Nitrate",
    limit: [0, 400],
    value: 47.8,
  },
  {
    isEditable: 23 !== 0,
    key: 10,
    label: "Ammonium Sulphate",
    limit: [0, 400],
    value: 23,
  },
  {
    isEditable: 4.9 !== 0,
    key: 11,
    label: "Anniline",
    limit: [0, 400],
    value: 4.9,
  },
  {
    isEditable: 5.5 !== 0,
    key: 12,
    label: "BisPhenolA",
    limit: [0, 400],
    value: 5.5,
  },
  {
    isEditable: 14.1 !== 0,
    key: 13,
    label: "Calcium Ammonium Nitrate",
    limit: [0, 400],
    value: 14.1,
  },
  {
    isEditable: 4.7 !== 0,
    key: 14,
    label: "Caprolactam",
    limit: [0, 400],
    value: 4.7,
  },
  {
    isEditable: 0.4 !== 0,
    key: 15,
    label: "Chloroprene",
    limit: [0, 400],
    value: 0.4,
  },
  {
    isEditable: 34.2 !== 0,
    key: 16,
    label: "Diammonium Phosphate",
    limit: [0, 400],
    value: 34.2,
  },
  {
    isEditable: 1.3 !== 0,
    key: 17,
    label: "Dimethyl Terephthalate",
    limit: [0, 400],
    value: 1.3,
  },
  {
    isEditable: 3.1 !== 0,
    key: 18,
    label: "Dioctyl Phthalate",
    limit: [0, 400],
    value: 3.1,
  },
  {
    isEditable: 132.6 !== 0,
    key: 19,
    label: "Ethylene",
    limit: [0, 400],
    value: 132.6,
  },
  {
    isEditable: 0 !== 0,
    key: 20,
    label: "Ethylene Chlorohydrin",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0 !== 0,
    key: 21,
    label: "Ethylene Glycol",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0 !== 0,
    key: 22,
    label: "Ethylene Oxide",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 15.1 !== 0,
    key: 23,
    label: "Formaldehyde",
    limit: [0, 400],
    value: 15.1,
  },
  {
    isEditable: 50 !== 0,
    key: 24,
    label: "H2",
    limit: [0, 400],
    value: 50,
  },
  {
    isEditable: 1.4 !== 0,
    key: 25,
    label: "Hexamethylenediamine",
    limit: [0, 400],
    value: 1.4,
  },
  {
    isEditable: 0.9 !== 0,
    key: 26,
    label: "Isophthalic Acid",
    limit: [0, 400],
    value: 0.9,
  },
  {
    isEditable: 1.8 !== 0,
    key: 27,
    label: "Maleic Anhydride",
    limit: [0, 400],
    value: 1.8,
  },
  {
    isEditable: 1.6 !== 0,
    key: 28,
    label: "Melamine",
    limit: [0, 400],
    value: 1.6,
  },
  {
    isEditable: 62.9 !== 0,
    key: 29,
    label: "Methanol",
    limit: [0, 400],
    value: 62.9,
  },
  {
    isEditable: 3.2 !== 0,
    key: 30,
    label: "Methyl Methacrylate",
    limit: [0, 400],
    value: 3.2,
  },
  {
    isEditable: 16.3 !== 0,
    key: 31,
    label: "Methyl Tertbutyl Ether",
    limit: [0, 400],
    value: 16.3,
  },
  {
    isEditable: 4.3 !== 0,
    key: 32,
    label: "Methylene Diphenyl Isocyanate",
    limit: [0, 400],
    value: 4.3,
  },
  {
    isEditable: 24.2 !== 0,
    key: 33,
    label: "Monoammonium Phosphate",
    limit: [0, 400],
    value: 24.2,
  },
  {
    isEditable: 48 !== 0,
    key: 34,
    label: "nitric acid",
    limit: [0, 400],
    value: 48,
  },
  {
    isEditable: 0.9 !== 0,
    key: 35,
    label: "Nitrile Butadiene",
    limit: [0, 400],
    value: 0.9,
  },
  {
    isEditable: 3.5 !== 0,
    key: 36,
    label: "Phthalic Anhydride",
    limit: [0, 400],
    value: 3.5,
  },
  {
    isEditable: 1.9 !== 0,
    key: 37,
    label: "Polyacrylonitrile",
    limit: [0, 400],
    value: 1.9,
  },
  {
    isEditable: 4.5 !== 0,
    key: 38,
    label: "Polyamide 6",
    limit: [0, 400],
    value: 4.5,
  },
  {
    isEditable: 2.6 !== 0,
    key: 39,
    label: "Polyamide 66",
    limit: [0, 400],
    value: 2.6,
  },
  {
    isEditable: 3.8 !== 0,
    key: 40,
    label: "Polybutadiene",
    limit: [0, 400],
    value: 3.8,
  },
  {
    isEditable: 3.9 !== 0,
    key: 41,
    label: "Polycarbonate",
    limit: [0, 400],
    value: 3.9,
  },
  {
    isEditable: 80.6 !== 0,
    key: 42,
    label: "Polyethylene",
    limit: [0, 400],
    value: 80.6,
  },
  {
    isEditable: 63.2 !== 0,
    key: 43,
    label: "Polyethylene Terephthalate",
    limit: [0, 400],
    value: 63.2,
  },
  {
    isEditable: 1.9 !== 0,
    key: 44,
    label: "Polymethyl Methacrylate",
    limit: [0, 400],
    value: 1.9,
  },
  {
    isEditable: 49.9 !== 0,
    key: 45,
    label: "Polypropylene",
    limit: [0, 400],
    value: 49.9,
  },
  {
    isEditable: 15.2 !== 0,
    key: 46,
    label: "Polystyrene",
    limit: [0, 400],
    value: 15.2,
  },
  {
    isEditable: 2.5 !== 0,
    key: 47,
    label: "Polyvinyl Acetate",
    limit: [0, 400],
    value: 2.5,
  },
  {
    isEditable: 30.3 !== 0,
    key: 48,
    label: "Polyvinyl Chloride",
    limit: [0, 400],
    value: 30.3,
  },
  {
    isEditable: 8.1 !== 0,
    key: 49,
    label: "PropyleneOxide",
    limit: [0, 400],
    value: 8.1,
  },
  {
    isEditable: 27.4 !== 0,
    key: 50,
    label: "Styrene",
    limit: [0, 400],
    value: 27.4,
  },
  {
    isEditable: 5.5 !== 0,
    key: 51,
    label: "StyreneAcryloniitrile",
    limit: [0, 400],
    value: 5.5,
  },
  {
    isEditable: 5.5 !== 0,
    key: 52,
    label: "StyreneButadiene",
    limit: [0, 400],
    value: 5.5,
  },
  {
    isEditable: 0 !== 0,
    key: 53,
    label: "Terephthalic Acid",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 2.5 !== 0,
    key: 54,
    label: "Toluene Diiosocyanate",
    limit: [0, 400],
    value: 2.5,
  },
  {
    isEditable: 169.3 !== 0,
    key: 55,
    label: "Urea",
    limit: [0, 400],
    value: 169.3,
  },
  {
    isEditable: 41.6 !== 0,
    key: 56,
    label: "Urea Ammonium Nitrate",
    limit: [0, 400],
    value: 41.6,
  },
  {
    isEditable: 5.9 !== 0,
    key: 57,
    label: "Vinyl Acetate",
    limit: [0, 400],
    value: 5.9,
  },
  {
    isEditable: 17.4 !== 0,
    key: 58,
    label: "Vinyl Chloride",
    limit: [0, 400],
    value: 17.4,
  },
  {
    isEditable: 0 !== 0,
    key: 59,
    label: "Energy",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0 !== 0,
    key: 60,
    label: "Electricity",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 39 !== 0,
    key: 61,
    label: "Ethylbenzene",
    limit: [0, 400],
    value: 39,
  },
  {
    isEditable: 7.7 !== 0,
    key: 62,
    label: "Acrylic acid",
    limit: [0, 400],
    value: 7.7,
  },
  {
    isEditable: 0 !== 0,
    key: 63,
    label: "Nitrobenzene",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 2.2 !== 0,
    key: 64,
    label: "Isopropanol",
    limit: [0, 400],
    value: 2.2,
  },
  {
    isEditable: 0 !== 0,
    key: 65,
    label: "Butyraldehyde",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 5.2 !== 0,
    key: 66,
    label: "N-Butanol",
    limit: [0, 400],
    value: 5.2,
  },
  {
    isEditable: 2.9 !== 0,
    key: 67,
    label: "EVA copolymer",
    limit: [0, 400],
    value: 2.9,
  },
  {
    isEditable: 1.5 !== 0,
    key: 68,
    label: "EPDM",
    limit: [0, 400],
    value: 1.5,
  },
  {
    isEditable: 0.07 !== 0,
    key: 69,
    label: "ENB",
    limit: [0, 400],
    value: 0.07,
  },
  {
    isEditable: 0 !== 0,
    key: 70,
    label: "Trans 1,4 hexadiene",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0 !== 0,
    key: 71,
    label: "Allyl chloride",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 2 !== 0,
    key: 72,
    label: "Epichlorohydrin",
    limit: [0, 400],
    value: 2,
  },
  {
    isEditable: 0 !== 0,
    key: 73,
    label: "Chlorine",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 4 !== 0,
    key: 74,
    label: "Glycerol",
    limit: [0, 400],
    value: 4,
  },
  {
    isEditable: 1.88 !== 0,
    key: 75,
    label: "Propylene Glycol",
    limit: [0, 400],
    value: 1.88,
  },
  {
    isEditable: 5.2 !== 0,
    key: 76,
    label: "Isobutanol",
    limit: [0, 400],
    value: 5.2,
  },
  {
    isEditable: 1.9 !== 0,
    key: 77,
    label: "Acetylene",
    limit: [0, 400],
    value: 1.9,
  },
  {
    isEditable: 3 !== 0,
    key: 78,
    label: "1,4 butanediol",
    limit: [0, 400],
    value: 3,
  },
  {
    isEditable: 10 !== 0,
    key: 79,
    label: "BADGE/DGEBA",
    limit: [0, 400],
    value: 10,
  },
  {
    isEditable: 1.3 !== 0,
    key: 80,
    label: "Acetaldehyde",
    limit: [0, 400],
    value: 1.3,
  },
  {
    isEditable: 0 !== 0,
    key: 81,
    label: "Diethanolamine (DEA)",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 4 !== 0,
    key: 82,
    label: "Ethyl acetate",
    limit: [0, 400],
    value: 4,
  },
  {
    isEditable: 0 !== 0,
    key: 83,
    label: "2-butoxyethanol/EGBE",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 47.7 !== 0,
    key: 84,
    label: "Ethylene dichloride",
    limit: [0, 400],
    value: 47.7,
  },
  {
    isEditable: 0 !== 0,
    key: 85,
    label: "2 ethylhexyl acrylate",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 4.8 !== 0,
    key: 86,
    label: "n butyl acrylate",
    limit: [0, 400],
    value: 4.8,
  },
  {
    isEditable: 0 !== 0,
    key: 87,
    label: "ethyl acrylate",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0.2 !== 0,
    key: 88,
    label: "methyl acrylate",
    limit: [0, 400],
    value: 0.2,
  },
  {
    isEditable: 0 !== 0,
    key: 89,
    label: "dinitrotoluene",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 2.6 !== 0,
    key: 90,
    label: "diethylene glycol",
    limit: [0, 400],
    value: 2.6,
  },
  {
    isEditable: 0 !== 0,
    key: 91,
    label: "dichloropropylene",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 1 !== 0,
    key: 92,
    label: "Hydrogen cyanide",
    limit: [0, 400],
    value: 1,
  },
  {
    isEditable: 1.002 !== 0,
    key: 93,
    label: "Acrolein",
    limit: [0, 400],
    value: 1.002,
  },
  {
    isEditable: 0 !== 0,
    key: 94,
    label: "Allyl alcohol",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0.5491 !== 0,
    key: 95,
    label: "Benzoic acid",
    limit: [0, 400],
    value: 0.5491,
  },
  {
    isEditable: 1 !== 0,
    key: 96,
    label: "Carbon disulphide",
    limit: [0, 400],
    value: 1,
  },
  {
    isEditable: 0 !== 0,
    key: 97,
    label: "Carbon tetrachloride",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0 !== 0,
    key: 98,
    label: "Chlorobenzene",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0.066 !== 0,
    key: 99,
    label: "Chloroform",
    limit: [0, 400],
    value: 0.066,
  },
  {
    isEditable: 0 !== 0,
    key: 100,
    label: "Crotonaldehyde",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0 !== 0,
    key: 101,
    label: "Cyclohexanol",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 6.4 !== 0,
    key: 102,
    label: "Cyclohexanone",
    limit: [0, 400],
    value: 6.4,
  },
  {
    isEditable: 0.3 !== 0,
    key: 103,
    label: "Peracetic acid",
    limit: [0, 400],
    value: 0.3,
  },
  {
    isEditable: 0 !== 0,
    key: 104,
    label: "Perchloroethylene",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0 !== 0,
    key: 105,
    label: "Phosgene",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0 !== 0,
    key: 106,
    label: "Toluene diamine",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0 !== 0,
    key: 107,
    label: "Trichloroethylene",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0.415 !== 0,
    key: 108,
    label: "Triethylene glycol",
    limit: [0, 400],
    value: 0.415,
  },
  {
    isEditable: 0 !== 0,
    key: 109,
    label: "Sodium nitrite",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0 !== 0,
    key: 110,
    label: "Nitrogen dioxide",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0 !== 0,
    key: 111,
    label: "Nitric oxide",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 2.84 !== 0,
    key: 112,
    label: "Potassium hydroxide",
    limit: [0, 400],
    value: 2.84,
  },
  {
    isEditable: 30 !== 0,
    key: 113,
    label: "Calcium hydroxide",
    limit: [0, 400],
    value: 30,
  },
  {
    isEditable: 1.7 !== 0,
    key: 114,
    label: "PBT",
    limit: [0, 400],
    value: 1.7,
  },
  {
    isEditable: 0 !== 0,
    key: 115,
    label: "Caprolactone",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0 !== 0,
    key: 116,
    label: "PCL",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0.5 !== 0,
    key: 117,
    label: "Pentaerithrytol",
    limit: [0, 400],
    value: 0.5,
  },
  {
    isEditable: 0 !== 0,
    key: 118,
    label: "Glyptal",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0 !== 0,
    key: 119,
    label: "SMA",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0.6 !== 0,
    key: 120,
    label: "PEG",
    limit: [0, 400],
    value: 0.6,
  },
  {
    isEditable: 1.46 !== 0,
    key: 121,
    label: "Tetrahydrofuran",
    limit: [0, 400],
    value: 1.46,
  },
  {
    isEditable: 1 !== 0,
    key: 122,
    label: "PTMEG",
    limit: [0, 400],
    value: 1,
  },
  {
    isEditable: 1.64 !== 0,
    key: 123,
    label: "PPG",
    limit: [0, 400],
    value: 1.64,
  },
  {
    isEditable: 0 !== 0,
    key: 124,
    label: "PBO",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0 !== 0,
    key: 125,
    label: "butylene oxide",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0 !== 0,
    key: 126,
    label: "PA/POM",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 1.9 !== 0,
    key: 127,
    label: "POM copolymer",
    limit: [0, 400],
    value: 1.9,
  },
  {
    isEditable: 0 !== 0,
    key: 128,
    label: "trioxane",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0.5 !== 0,
    key: 129,
    label: "PPO",
    limit: [0, 400],
    value: 0.5,
  },
  {
    isEditable: 0 !== 0,
    key: 130,
    label: "2,6 dimethylphenol",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0 !== 0,
    key: 131,
    label: "Hypochlorous acid",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 14.8 !== 0,
    key: 132,
    label: "Hydrochloric acid",
    limit: [0, 400],
    value: 14.8,
  },
  {
    isEditable: 231 !== 0,
    key: 133,
    label: "sulphuric acid",
    limit: [0, 400],
    value: 231,
  },
  {
    isEditable: 0 !== 0,
    key: 134,
    label: "hydroxyl amine",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 0 !== 0,
    key: 135,
    label: "nitrous acid",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 86.63 !== 0,
    key: 136,
    label: "Phosphoric acid",
    limit: [0, 400],
    value: 86.63,
  },
  {
    isEditable: 0 !== 0,
    key: 137,
    label: "Sucrose",
    limit: [0, 400],
    value: 0,
  },
  {
    isEditable: 79.92 !== 0,
    key: 138,
    label: "Ethanol",
    limit: [0, 400],
    value: 79.92,
  },
];
