name: Build and push docker image for linux/arm64 and linux/amd64

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docker-build:
    name: Build docker image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform-arch:
          - linux/amd64
          - linux/arm64
          
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}

      # ACTIONS_RUNTIME_TOKEN, ACTIONS_RUNTIME_URL should be exposed
    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v3
      
    - name: docker build and push
      run: |-
        echo "building docker images..."
        platform = $(echo ${{ matrix.platform-arch }} | sed 's/.*\///')
        
        docker buildx build --platform=${{ matrix.platform-arch }} \
        -t mahesh1598/cmi-tool-server:$platform \
        --cache-to type=gha,mode=max \
        --cache-from type=gha \
        --push \
        -f Dockerfile .
        
    - name: docker pull
      run: |-
        platform = $(echo ${{ matrix.platform-arch }} | sed 's/.*\///')
        docker pull --platform=${{  matrix.platform-arch }} mahesh1598/cmi-tool-server:$platform
        
    - name: docker build test
      env:
        DOCKER_USERNAME: 'mahesh1598'
      run: |-
        echo "[TEST] building docker images..."
        platform = $(echo ${{ matrix.platform-arch }} | sed 's/.*\///')
        docker run --rm -t $DOCKER_USERNAME/cmi-tool-server:$platform uname -m
